apiVersion: v1
kind: Pod
metadata:
  name: devops-challenge
spec:
  containers:
  - name: app
    image: devops-challenge:latest
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
